version: '3'
services:
  nextjs:
    build:
      context: .
    container_name: nextjs
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
  cypress:
    image: "cypress/included:8.3.0"
    container_name: cypress
    depends_on:
      - nextjs
    environment:
      - CYPRESS_baseUrl=http://nextjs:3000
    working_dir: /cypress
    volumes:
      - ./:/cypress